export enum SCREENS {
  HOME = "/",
  PORTFOLIO = "/portfolio",
  ABOUT_US = "/about-us",
  JOIN_US = /*'/join-us'*/ "#",
  SERVICES = /*'/services'*/ "#",
  CONTACTS = "/contacts",
  META_MODERN_PRIVACY = "/privacy",
  TOD = "/ToD",
  TOD_PRIVACY = "/ToD/privacy",
  TOD_TERMS = "/ToD/terms",
  TIME_ZO = "/TimeZo",
  TIME_ZO_PRIVACY = "/TimeZo/privacy",
  WORLD_CLOCK_PRIVACY = "/WorldClock/privacy",
  TIME_ZO_TERMS = "/TimeZo/terms",
  WORLD_CLOCK_TERMS = "/WorldClock/terms",
  NeverHaveEver = "/NeverHaveEver",
  NeverEver_PRIVACY = "/NeverEver/privacy",
  NeverEver_TERMS = "/NeverEver/terms",
  CALM_CATS = "/CalmCats",
  CALM_CATS_PRIVACY = "/CalmCats/privacy",
  CALM_CATS_TERMS = "/CalmCats/terms",
  BB_LIST = "/BB-list",
  CONTRACTIONS_PRIVACY = "/Contractions/privacy",
  CONTRACTIONS_TERMS = "/Contractions/terms",
}
